import { useState, useEffect } from "react";
import "./App.css";
import type {
  ViewType,
  ChatObject,
  MessageObject,
  DocumentObject,
} from "./types";
import Sidebar from "./features/sidebar/Sidebar";
import KnowledgeBase from "./features/knowledgeBase/KnowledgeBase";
import Chat from "./features/chat/Chat";
import { getKnowledgeBaseDocuments } from "./features/knowledgeBase/services/KnowledgeBaseApi";

function App() {
  const [documentList, setDocumentList] = useState<DocumentObject[]>([]);
  const [activeView, setActiveView] = useState<ViewType>("knowledgeBase");
  const [chats, setChats] = useState<Record<string, ChatObject>>({});
  const [selectedChatId, setChatId] = useState<string | null>(null);
  const [chatCounter, setChatCounter] = useState<number>(1);

  function handleSetActiveView(view: ViewType) {
    setActiveView(view);
  }

  function handleSelectChat(chatId: string) {
    setChatId(chatId);
    setActiveView("chat");
  }

  function handleCreateNewChat() {
    const newId = crypto.randomUUID();
    const newChat: ChatObject = _createChatObject(newId);
    setChats({ ...chats, [newId]: newChat });
    setChatCounter(chatCounter + 1);
    handleSelectChat(newId);
    return newChat;
  }

  function handleDeleteChat(chatId: string) {
    if (chatId === selectedChatId) {
      const newId = crypto.randomUUID();
      const newChat = _createChatObject(newId);
      const { [chatId]: _, ...rest } = chats;

      setChats({ ...rest, [newId]: newChat });
      setChatCounter(chatCounter + 1);
      handleSelectChat(newId);
    } else {
      const { [chatId]: _, ...rest } = chats;
      setChats(rest);
    }
  }

  function handleRenameChat(id: string, newTitle: string) {
    const newChatTitle = newTitle.trim() === "" ? chats[id].title : newTitle;
    setChats({
      ...chats,
      [id]: { ...chats[id], title: newChatTitle, updatedAt: new Date() },
    });
  }

  // Updated to handle sessionId management
  function handleUpdateChatMessageList(
    id: string,
    newMessage: MessageObject,
    sessionId?: string
  ) {
    setChats((prevChats) => {
      if (!prevChats[id]) {
        return prevChats; // No-op, return unchanged state
      }

      const updatedChat = {
        ...prevChats[id],
        updatedAt: new Date(),
        messages: [...prevChats[id].messages, newMessage],
      };

      // Update sessionId if provided (from backend response)
      if (sessionId) {
        updatedChat.sessionId = sessionId;
      }

      return {
        ...prevChats,
        [id]: updatedChat,
      };
    });
  }

  // Handle session expiration by creating a new chat
  function handleSessionExpired(expiredChatId: string) {
    console.log("Session expired for chat:", expiredChatId);

    // Create a new chat to replace the expired one
    const newId = crypto.randomUUID();
    const newChat = _createChatObject(newId);

    setChats((prevChats) => {
      const { [expiredChatId]: _, ...rest } = prevChats;
      return { ...rest, [newId]: newChat };
    });

    setChatCounter(chatCounter + 1);
    handleSelectChat(newId);

    // You might want to show a toast notification here
    alert("Created new chat due to session expiration");
  }

  function _createChatObject(newId: string): ChatObject {
    const currentDateTime: Date = new Date();
    return {
      id: newId,
      title: `New Chat ${chatCounter}`,
      messages: [],
      createdAt: currentDateTime,
      updatedAt: currentDateTime,
      // sessionId will be generated by backend on first message
    };
  }

  useEffect(() => {
    async function fetchInitialDocs() {
      try {
        const response = await getKnowledgeBaseDocuments();
        setDocumentList(response.documentDetails);
      } catch (error) {
        console.error("Failed to load initial documents:", error);
      }
    }

    fetchInitialDocs();
  }, []);

  return (
    <div className="app-container">
      <div className="sidebar">
        <Sidebar
          chats={chats}
          selectedChatId={selectedChatId}
          handleCreateNewChat={handleCreateNewChat}
          handleDeleteChat={handleDeleteChat}
          handleRenameChat={handleRenameChat}
          handleSelectChat={handleSelectChat}
          handleSetActiveView={handleSetActiveView}
        />
      </div>
      <div className="main-content">
        {activeView === "knowledgeBase" ? (
          <KnowledgeBase
            documentList={documentList}
            setDocumentList={setDocumentList}
          />
        ) : selectedChatId && chats[selectedChatId] ? (
          <Chat
            selectedChat={chats[selectedChatId]}
            handleUpdateChatMessageList={handleUpdateChatMessageList}
            onSessionExpired={handleSessionExpired}
          />
        ) : (
          <div>Select a chat to get started</div>
        )}
      </div>
    </div>
  );
}

export default App;
